dist: xenial
language: minimal

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - deploy

env:
# Carefull, also set it in the deploy section!
- NOTES_FILE=main

services:
- docker

script:
- docker run --rm -v $(pwd):/notes blang/latex /bin/bash -c "cd /notes; ./build.sh $NOTES_FILE"
- "./test.sh $NOTES_FILE"

deploy:
  provider: releases
  api_key:
    secure: gOf79nk3ghOyWsJzkQs/Uob1wzyrAUBQ5PPYMmu10m6BTH0h8rZBaM5UkqFcKCKjMDVdzL2NA0Q40V/th+4uo8GnyPwwq83U0Yo1cQIThzg9n2ffiKDipb4C3temuW/fSNbXqiPF0f1/CATcsg8eLThCc/RPTu9En6HHB0qfbSXvPuAggpWr1H8l64ou3cDANI24rwoxdWAAT+z2TEct3eWGsv2oP8t5dxLYvqAi4iTtcXai3tii0wXC1D/K2K79uY3bsoUSzSjqdxyIF9NffS6Vi3fz+u17Xj1XRbdJhxYIDhNFOE1GZYLSIwa1CBOqM2+dWA/d5lqqrGQf0P6RualeCV5YWa7C9476Y2sBxg+QxcFt1uPcvctN/Dcuq2nTj7QyZlzaw4KmD/heaOKs/PN3LPLCUbdoDHX16QcAwfs/1ckZ5t6FUWno90/+VkMFyDxReYvky5JYgWWGZR7vbJ9i4u5ZXr0QkSA+JZ0T4roYx3h8E7+kMUMrHDA4hm49pTiS0WGcHUtrqywYlaS5M/t+NsPkgyLhZWx7Ds8foI5qw2ujfD562wkrAOhmkJOUs7vFI9j0k7tXbY4qhlTIceotnFbiJBEz/jVMmaj3mBUR9B1p/8qqiePNmtDNuNKCOcGFFD/iDALcR1WAn2JYQmWeTJ4BKjpRFhKihQtn+Jc=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: icl-notes/m3p20
